### ISSUE TITLE
XcmDDCErrorToString() returns a empty string

### ISSUE THREAD

**Issue by yars068** [oyranos-cms/libxcm#2]
Hello. I use xcm-0.5.2 (and libXcm-0.5.2) as a part of x package series in Slackware (I use Slackware64-current). Currently, they used with X server version 1.18 together, and I noticed that this code breaks the correct work of xcmddc. The problem is in the code:

```
const char *   XcmDDCErrorToString   ( XCM_DDC_ERROR_e     error )
{
  const char * text = 0;
  switch(error)
  {
  case XCM_DDC_OK: text = ""; break;
```

In that case, xcmddc will return an empty string, which is incorrect, according to xcm(1):

```
--identify dump the error code as integer to stdout
```

The manpage is dated dec-30-2010, but as I see no changes since that date. So my question is what package should be fixed: xcm or libxcm?

**Comment by beku** [comment]
src/xcmddc.c +177 is wrong
needs to be:
printf( "%s\n", error);

That bug might have prevented the i2c rules from working.

Thanks for pointing out. Waiting for your merge or patch.

**Comment by yars068** [comment]
Patch is here: https://github.com/oyranos-cms/xcm/pull/1

> That bug might have prevented the i2c rules from working.

It so already, because of this I noticed a bug.

**Comment by beku** [comment]
Thanks for the report and fix.
